services:
  # Backend
  - type: web
    name: shieldsafe-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  # Frontend
  - type: web
    name: shieldsafe-frontend
    env: static
    rootDir: frontend
    buildCommand: ""
    startCommand: ""